# Generated by Django 4.0.4 on 2022-05-05 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('product_description', models.CharField(max_length=40)),
                ('product_unit', models.CharField(max_length=40)),
                ('product_price', models.FloatField()),
                ('product_quantity', models.IntegerField(max_length=10)),
                ('product_status', models.IntegerField(max_length=10)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
