# Generated by Django 4.0.4 on 2022-05-05 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('product', '0003_alter_product_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
            preserve_default=False,
        ),
    ]
