# Generated by Django 4.0.4 on 2022-05-28 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_supplier',
        ),
    ]
