# Generated by Django 4.0.4 on 2022-05-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_supplier_phone'),
        ('product', '0008_remove_product_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_supplier',
            field=models.ManyToManyField(blank=True, related_name='product_supplier_map', to='supplier.supplier'),
        ),
    ]
